#!/usr/bin/env python3
"""Generate Monkey C palette mapping from the committed design tokens."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
def main():
    themes=json.loads((ROOT/'resources/themes.json').read_text())
    colors=sorted(set().union(*(t['colors'] for t in themes)))
    out=['// Generated by tools/generate_palettes.py; edit resources/themes.json.','module PrismelierPalette {','    function color(value, theme) {','        if (theme == 0) { return value; }','        switch (value) {']
    for color in colors:
        out.append('            case 0x'+color+':')
        for i,t in enumerate(themes[1:],1):out.append(f'                if (theme == {i}) {{ return 0x{t["colors"].get(color,color)}; }}')
        out.append('                break;')
    out+=['        }','        return value;','    }','}']
    (ROOT/'source/PrismelierPalette.mc').write_text('\n'.join(out)+'\n')
if __name__=='__main__':main()
