// Generated by tools/generate_palettes.py; edit resources/themes.json.
module PrismelierPalette {
    function color(value, theme) {
        if (theme == 0) { return value; }
        switch (value) {
            case 0x050E12:
                if (theme == 1) { return 0x091210; }
                if (theme == 2) { return 0x0F1011; }
                if (theme == 3) { return 0x060B12; }
                break;
            case 0x071214:
                if (theme == 1) { return 0x0A1412; }
                if (theme == 2) { return 0x111212; }
                if (theme == 3) { return 0x070D14; }
                break;
            case 0x080F13:
                if (theme == 1) { return 0x0A1311; }
                if (theme == 2) { return 0x101111; }
                if (theme == 3) { return 0x070C13; }
                break;
            case 0x091B23:
                if (theme == 1) { return 0x122320; }
                if (theme == 2) { return 0x1D2020; }
                if (theme == 3) { return 0x0C1623; }
                break;
            case 0x102226:
                if (theme == 1) { return 0x142622; }
                if (theme == 2) { return 0x1F2223; }
                if (theme == 3) { return 0x0D1826; }
                break;
            case 0x122325:
                if (theme == 1) { return 0x152824; }
                if (theme == 2) { return 0x222627; }
                if (theme == 3) { return 0x112238; }
                break;
            case 0x175452:
                if (theme == 1) { return 0x2C544C; }
                if (theme == 2) { return 0x454C4D; }
                if (theme == 3) { return 0x1D3554; }
                break;
            case 0x183B3B:
                if (theme == 1) { return 0x284941; }
                if (theme == 2) { return 0x343C3C; }
                if (theme == 3) { return 0x203A56; }
                break;
            case 0x224142:
                if (theme == 1) { return 0x23423B; }
                if (theme == 2) { return 0x363B3D; }
                if (theme == 3) { return 0x172A42; }
                break;
            case 0x22433F:
                if (theme == 1) { return 0x23433C; }
                if (theme == 2) { return 0x373C3E; }
                if (theme == 3) { return 0x172A43; }
                break;
            case 0x241620:
                if (theme == 1) { return 0x241F19; }
                if (theme == 2) { return 0x211F1C; }
                if (theme == 3) { return 0x111724; }
                break;
            case 0x243F42:
                if (theme == 1) { return 0x23423B; }
                if (theme == 2) { return 0x363B3D; }
                if (theme == 3) { return 0x172A42; }
                break;
            case 0x263D3D:
                if (theme == 1) { return 0x203D37; }
                if (theme == 2) { return 0x323738; }
                if (theme == 3) { return 0x15273D; }
                break;
            case 0x27645D:
                if (theme == 1) { return 0x204C45; }
                if (theme == 2) { return 0x445B58; }
                if (theme == 3) { return 0x244A70; }
                break;
            case 0x284D4D:
                if (theme == 1) { return 0x284D45; }
                if (theme == 2) { return 0x404547; }
                if (theme == 3) { return 0x1B314D; }
                break;
            case 0x295F5D:
                if (theme == 1) { return 0x325F56; }
                if (theme == 2) { return 0x4E5657; }
                if (theme == 3) { return 0x213C5F; }
                break;
            case 0x2F625C:
                if (theme == 1) { return 0x336258; }
                if (theme == 2) { return 0x51585A; }
                if (theme == 3) { return 0x223E62; }
                break;
            case 0x326960:
                if (theme == 1) { return 0x37695E; }
                if (theme == 2) { return 0x575F61; }
                if (theme == 3) { return 0x254369; }
                break;
            case 0x334945:
                if (theme == 1) { return 0x264942; }
                if (theme == 2) { return 0x3C4243; }
                if (theme == 3) { return 0x1A2E49; }
                break;
            case 0x335657:
                if (theme == 1) { return 0x2E574E; }
                if (theme == 2) { return 0x484E50; }
                if (theme == 3) { return 0x1E3757; }
                break;
            case 0x344741:
                if (theme == 1) { return 0x254740; }
                if (theme == 2) { return 0x3B4041; }
                if (theme == 3) { return 0x192D47; }
                break;
            case 0x34877D:
                if (theme == 1) { return 0x75877F; }
                if (theme == 2) { return 0x757C7C; }
                if (theme == 3) { return 0x5C7187; }
                break;
            case 0x365E59:
                if (theme == 1) { return 0x315E55; }
                if (theme == 2) { return 0x4E5556; }
                if (theme == 3) { return 0x213C5E; }
                break;
            case 0x3C6260:
                if (theme == 1) { return 0x336258; }
                if (theme == 2) { return 0x51585A; }
                if (theme == 3) { return 0x223E62; }
                break;
            case 0x3D3433:
                if (theme == 1) { return 0x203D37; }
                if (theme == 2) { return 0x323738; }
                if (theme == 3) { return 0x15273D; }
                break;
            case 0x3E211E:
                if (theme == 1) { return 0x3E2C1E; }
                if (theme == 2) { return 0x39322B; }
                if (theme == 3) { return 0x3E3321; }
                break;
            case 0x3F314C:
                if (theme == 1) { return 0x4C4236; }
                if (theme == 2) { return 0x46413A; }
                if (theme == 3) { return 0x23324C; }
                break;
            case 0x452744:
                if (theme == 1) { return 0x443B30; }
                if (theme == 2) { return 0x3E3831; }
                if (theme == 3) { return 0x202D45; }
                break;
            case 0x487B72:
                if (theme == 1) { return 0x417B6F; }
                if (theme == 2) { return 0x666F71; }
                if (theme == 3) { return 0x2B4E7B; }
                break;
            case 0x4B9D95:
                if (theme == 1) { return 0x889D94; }
                if (theme == 2) { return 0x889090; }
                if (theme == 3) { return 0x6B839D; }
                break;
            case 0x4D3C2E:
                if (theme == 1) { return 0x4D3626; }
                if (theme == 2) { return 0x473F35; }
                if (theme == 3) { return 0x4D3F29; }
                break;
            case 0x4F958B:
                if (theme == 1) { return 0x81958C; }
                if (theme == 2) { return 0x818989; }
                if (theme == 3) { return 0x667D95; }
                break;
            case 0x503949:
                if (theme == 1) { return 0x504538; }
                if (theme == 2) { return 0x4A443D; }
                if (theme == 3) { return 0x253450; }
                break;
            case 0x5D3527:
                if (theme == 1) { return 0x5D412E; }
                if (theme == 2) { return 0x564C40; }
                if (theme == 3) { return 0x5D4C31; }
                break;
            case 0x5D3854:
                if (theme == 1) { return 0x5D5142; }
                if (theme == 2) { return 0x564F47; }
                if (theme == 3) { return 0x2B3D5D; }
                break;
            case 0x606775:
                if (theme == 1) { return 0x606775; }
                if (theme == 2) { return 0x606775; }
                if (theme == 3) { return 0x606775; }
                break;
            case 0x644154:
                if (theme == 1) { return 0x645747; }
                if (theme == 2) { return 0x5C554D; }
                if (theme == 3) { return 0x2E4164; }
                break;
            case 0x69465B:
                if (theme == 1) { return 0x695B4A; }
                if (theme == 2) { return 0x615950; }
                if (theme == 3) { return 0x314469; }
                break;
            case 0x6B4839:
                if (theme == 1) { return 0x6B4B34; }
                if (theme == 2) { return 0x625749; }
                if (theme == 3) { return 0x6B5739; }
                break;
            case 0x6BE4DE:
                if (theme == 1) { return 0xB1CCC0; }
                if (theme == 2) { return 0xB9C8C8; }
                if (theme == 3) { return 0x8FAFD1; }
                break;
            case 0x6E4B3A:
                if (theme == 1) { return 0x6E4D36; }
                if (theme == 2) { return 0x655A4C; }
                if (theme == 3) { return 0x6E5A3A; }
                break;
            case 0x6F494D:
                if (theme == 1) { return 0x6F4E36; }
                if (theme == 2) { return 0x665A4C; }
                if (theme == 3) { return 0x6F5B3B; }
                break;
            case 0x724060:
                if (theme == 1) { return 0x726350; }
                if (theme == 2) { return 0x696157; }
                if (theme == 3) { return 0x354A72; }
                break;
            case 0x74ACA0:
                if (theme == 1) { return 0x95ACA2; }
                if (theme == 2) { return 0x959E9E; }
                if (theme == 3) { return 0x7690AC; }
                break;
            case 0x75513D:
                if (theme == 1) { return 0x755239; }
                if (theme == 2) { return 0x6C5F50; }
                if (theme == 3) { return 0x755F3E; }
                break;
            case 0x777F70:
                if (theme == 1) { return 0x437F72; }
                if (theme == 2) { return 0x697275; }
                if (theme == 3) { return 0x2C507F; }
                break;
            case 0x786D82:
                if (theme == 1) { return 0x7F8274; }
                if (theme == 2) { return 0x85817B; }
                if (theme == 3) { return 0x758399; }
                break;
            case 0x805745:
                if (theme == 1) { return 0x805A3F; }
                if (theme == 2) { return 0x766858; }
                if (theme == 3) { return 0x806844; }
                break;
            case 0x80665C:
                if (theme == 1) { return 0x805A3F; }
                if (theme == 2) { return 0x766858; }
                if (theme == 3) { return 0x806844; }
                break;
            case 0x84644C:
                if (theme == 1) { return 0x84644C; }
                if (theme == 2) { return 0x84644C; }
                if (theme == 3) { return 0x84644C; }
                break;
            case 0x85506D:
                if (theme == 1) { return 0x85735E; }
                if (theme == 2) { return 0x7A7166; }
                if (theme == 3) { return 0x3E5785; }
                break;
            case 0x86557A:
                if (theme == 1) { return 0x86745F; }
                if (theme == 2) { return 0x7B7267; }
                if (theme == 3) { return 0x3E5786; }
                break;
            case 0x8B6544:
                if (theme == 1) { return 0x8B6244; }
                if (theme == 2) { return 0x80715F; }
                if (theme == 3) { return 0x8B714A; }
                break;
            case 0x90E6FF:
                if (theme == 1) { return 0xCEEDDF; }
                if (theme == 2) { return 0xDDEBEB; }
                if (theme == 3) { return 0xA2C7ED; }
                break;
            case 0x916B49:
                if (theme == 1) { return 0x916647; }
                if (theme == 2) { return 0x857664; }
                if (theme == 3) { return 0x91764D; }
                break;
            case 0xA04D30:
                if (theme == 1) { return 0x7D402C; }
                if (theme == 2) { return 0x70462F; }
                if (theme == 3) { return 0x735022; }
                break;
            case 0xA09785:
                if (theme == 1) { return 0xA09785; }
                if (theme == 2) { return 0xA09785; }
                if (theme == 3) { return 0xA09785; }
                break;
            case 0xA16E4C:
                if (theme == 1) { return 0xA1714F; }
                if (theme == 2) { return 0x94836F; }
                if (theme == 3) { return 0xA18355; }
                break;
            case 0xB56942:
                if (theme == 1) { return 0xB57F59; }
                if (theme == 2) { return 0xA7937C; }
                if (theme == 3) { return 0xB59460; }
                break;
            case 0xC7FF70:
                if (theme == 1) { return 0xDECFB1; }
                if (theme == 2) { return 0xE9DFC9; }
                if (theme == 3) { return 0xCBE0F5; }
                break;
            case 0xD59DFF:
                if (theme == 1) { return 0xEDCEA7; }
                if (theme == 2) { return 0xEBD8C3; }
                if (theme == 3) { return 0x6E9BED; }
                break;
            case 0xD6D9BF:
                if (theme == 1) { return 0xD5CBB0; }
                if (theme == 2) { return 0xDCD5C5; }
                if (theme == 3) { return 0xBFCEDA; }
                break;
            case 0xD98B52:
                if (theme == 1) { return 0xC68B61; }
                if (theme == 2) { return 0xA78F72; }
                if (theme == 3) { return 0xB99762; }
                break;
            case 0xF2BF8C:
                if (theme == 1) { return 0xEDA674; }
                if (theme == 2) { return 0xDFC5A6; }
                if (theme == 3) { return 0xEDC27E; }
                break;
            case 0xF2EDD8:
                if (theme == 1) { return 0xE8DCC5; }
                if (theme == 2) { return 0xE9E0D0; }
                if (theme == 3) { return 0xDCE5EC; }
                break;
            case 0xF474E8:
                if (theme == 1) { return 0x6AB8AA; }
                if (theme == 2) { return 0xC4A583; }
                if (theme == 3) { return 0xE7AD61; }
                break;
            case 0xF5F5DB:
                if (theme == 1) { return 0xEDE2C4; }
                if (theme == 2) { return 0xE1DCCF; }
                if (theme == 3) { return 0xD0E0ED; }
                break;
            case 0xFFB65D:
                if (theme == 1) { return 0xEDA674; }
                if (theme == 2) { return 0xEBD0AF; }
                if (theme == 3) { return 0xEDC27E; }
                break;
            case 0xFFC9FA:
                if (theme == 1) { return 0xC4E6D8; }
                if (theme == 2) { return 0xECE1D0; }
                if (theme == 3) { return 0xFADEAB; }
                break;
        }
        return value;
    }
}
